apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: immich-postgres
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: immich-postgres
    app.kubernetes.io/service: immich-postgres
    helm.sh/chart: app-template-5.1.0
  name: immich-postgres
  namespace: immich
spec:
  ports:
    - name: postgres
      port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    app.kubernetes.io/controller: main
    app.kubernetes.io/instance: immich-postgres
    app.kubernetes.io/name: immich-postgres
  type: ClusterIP
