apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: retained-storage
  namespace: argocd
spec:
  destination:
    namespace: local-path-storage
    server: https://kubernetes.default.svc
  project: default
  source:
    path: ./generated/manifests/prod-home/retained-storage
    repoURL: https://github.com/dvicory/homelab.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
