apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: sonarr
  namespace: argocd
spec:
  destination:
    namespace: media
    server: https://kubernetes.default.svc
  project: prod-home
  source:
    path: ./generated/manifests/prod-home/sonarr
    repoURL: https://github.com/dvicory/homelab.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m
      limit: 5
    syncOptions:
      - FailOnSharedResource=true
      - ServerSideApply=true
