apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-dns
  namespace: argocd
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: default
  source:
    path: ./generated/manifests/prod-home/cluster-dns
    repoURL: https://github.com/dvicory/homelab.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
