apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    argocd.argoproj.io/sync-options: Prune=false,Delete=false
  name: immich-library
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Ti
  claimRef:
    name: immich-library
    namespace: immich
  local:
    path: /srv/state/immich-library
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - compute-1
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  volumeMode: Filesystem
