apiVersion: v1
data:
  server.toml: |
    version = "2"
    bindaddress = "0.0.0.0:8443"
    db_path = "/data/kanidm.db"
    tls_chain = "/etc/kanidm/tls/tls.crt"
    tls_key = "/etc/kanidm/tls/tls.key"
    domain = "idm.plus2.danielvicory.dev"
    origin = "https://idm.plus2.danielvicory.dev"
    [online_backup]
    path = "/data/backups/"
    schedule = "00 22 * * *"
kind: ConfigMap
metadata:
  name: kanidm-config
  namespace: identity
