apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kanidm-client-secret-argocd
  namespace: argocd
rules:
  - apiGroups:
      - ""
    resourceNames:
      - argocd-kanidm-oidc
    resources:
      - secrets
    verbs:
      - get
      - patch
