apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kanidm-client-secret-oidc-radarr
  namespace: gateway
rules:
  - apiGroups:
      - ""
    resourceNames:
      - oidc-radarr
    resources:
      - secrets
    verbs:
      - get
      - patch
