apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kanidm-client-secret-oidc-sabnzbd
  namespace: gateway
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kanidm-client-secret-oidc-sabnzbd
subjects:
  - kind: ServiceAccount
    name: kanidm-provision
    namespace: identity
