apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kanidm-client-secret-oidc-sabnzbd
  namespace: gateway
rules:
  - apiGroups:
      - ""
    resourceNames:
      - oidc-sabnzbd
    resources:
      - secrets
    verbs:
      - get
      - patch
