apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kanidm-client-secret-oidc-prowlarr
  namespace: gateway
rules:
  - apiGroups:
      - ""
    resourceNames:
      - oidc-prowlarr
    resources:
      - secrets
    verbs:
      - get
      - patch
