apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kanidm-client-secret-household-admin
  namespace: gateway
rules:
  - apiGroups:
      - ""
    resourceNames:
      - oidc-client
    resources:
      - secrets
    verbs:
      - get
      - patch
