apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    argocd.argoproj.io/sync-options: Prune=false,Delete=false
  name: monitoring-loki
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 20Gi
  claimRef:
    name: loki-data
    namespace: monitoring
  local:
    path: /srv/state/monitoring-loki
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - compute-1
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  volumeMode: Filesystem
