apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: jellyfin
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: jellyfin
    app.kubernetes.io/service: jellyfin
    helm.sh/chart: app-template-5.1.0
  name: jellyfin
  namespace: jellyfin
spec:
  ports:
    - name: http
      port: 8096
      protocol: TCP
      targetPort: 8096
  selector:
    app.kubernetes.io/controller: main
    app.kubernetes.io/instance: jellyfin
    app.kubernetes.io/name: jellyfin
  type: ClusterIP
